<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

?>
<?php
// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis

/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper(Magento\Catalog\Helper\Output::class);
?>
<?php if (!$_productCollection->count()) :?>
    <div class="message info empty"><div><?= $block->escapeHtml(__('We can\'t find products matching the selection.')) ?></div></div>
    <?php else :?>
        <?= $block->getToolbarHtml() ?>
        <?= $block->getAdditionalHtml() ?>
        <?php
        if ($block->getMode() == 'grid') {
            $viewMode = 'grid';
            $imageDisplayArea = 'category_page_grid';
            $showDescription = false;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
        } else {
            $viewMode = 'list';
            $imageDisplayArea = 'category_page_list';
            $showDescription = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
        }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <div class="products wrapper <?= /* @noEscape */ $viewMode ?> products-<?= /* @noEscape */ $viewMode ?>">
        <ol class="products list items product-items">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product) :?>
                <li class="item product product-item">
                    <div class="product-item-info" data-container="product-<?= /* @noEscape */ $viewMode ?>">
                        <?php
                        $productImage = $block->getImage($_product, $imageDisplayArea);
                        if ($pos != null) {
                            $position = ' style="left:' . $productImage->getWidth() . 'px;'
                            . 'top:' . $productImage->getHeight() . 'px;"';
                        }
                        ?>
                        <?php // Product Image ?>
                        <a href="<?= $block->escapeUrl($_product->getProductUrl()) ?>"
                           class="product photo product-item-photo"
                           tabindex="-1">
                           <?= $productImage->toHtml() ?>
                       </a>
                       <div class="product details product-item-details">
                        <!-- Actribute new or new shade -->
                        <?php
                        $NewOrNewshade = $_product->getResource()->getAttribute('raww_label');
                        if ($NewOrNewshade) {
                            $class = "";
                            $NewOrNewshade = $NewOrNewshade->getFrontend()->getValue($_product);
                            if ($NewOrNewshade === 'NEW') {
                                $class = 'new-label';
                            } else if (
                                $NewOrNewshade === 'NEW SHADE'
                            ) {
                                $class = 'new-shade-label';
                            }
                            echo "<div class=$class>" . $NewOrNewshade . "</div>";
                        }
                        ?>
                        <!--End Actribute new or new shade  -->

                        <?php
                        $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                        ?>
                        <strong class="product name product-item-name">
                            <a class="product-item-link"
                            href="<?= $block->escapeUrl($_product->getProductUrl()) ?>">
                            <?= /* @noEscape */ $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                        </a>
                    </strong>

                    <?= $block->getReviewsSummaryHtml($_product, $templateType) ?>
                    <?= /* @noEscape */ $block->getProductPrice($_product) ?>

                    <?php if ($_product->isAvailable()) :?>
                        <?= $block->getProductDetailsHtml($_product) ?>
                    <?php endif; ?>

                    <!-- color tam -->
                    <div class="list-color">
                        List color
                    </div>
                    
                    <!-- view more -->
                     <a href="<?= $block->escapeUrl($_product->getProductUrl()) ?>" class="button_mob" >
                           View More
                     </a>

                    <div class="product-item-inner">
                        <div class="product actions product-item-actions"<?= strpos($pos, $viewMode . '-actions') ? $block->escapeHtmlAttr($position) : '' ?>>
                            <div class="actions-primary"<?= strpos($pos, $viewMode . '-primary') ? $block->escapeHtmlAttr($position) : '' ?>>
                                <?php if ($_product->isSaleable()) :?>
                                    <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                    <form data-role="tocart-form"
                                    data-product-sku="<?= $block->escapeHtmlAttr($_product->getSku()) ?>"
                                    action="<?= $block->escapeUrl($postParams['action']) ?>"
                                    method="post">
                                    <input type="hidden"
                                    name="product"
                                    value="<?= /* @noEscape */ $postParams['data']['product'] ?>">
                                    <input type="hidden" name="<?= /* @noEscape */ Action::PARAM_NAME_URL_ENCODED ?>"
                                    value="<?= /* @noEscape */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                    <?= $block->getBlockHtml('formkey') ?>

                                    <div class="field qty">
                                        <div class="control">
                                            <span class="minus-btn qty-btn"></span>
                                            <input type="number" name="qty" id="qty" maxlength="12" value="1" title="Qty" class="input-text qty" data-validate="null">
                                            <span class="plus-btn qty-btn"></span>
                                        </div>
                                    </div>
                                    
                                    <button type="submit"
                                    title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>"
                                    class="action tocart primary add-button">
                                    <span><?= $block->escapeHtml(__('Add to Bag')) ?></span>
                                </button>
                            </form>
                            <?php else :?>
                                <?php if ($_product->isAvailable()) :?>
                                    <div class="stock available"><span><?= $block->escapeHtml(__('In stock')) ?></span></div>
                                    <?php else :?>
                                        <div class="stock unavailable"><span><?= $block->escapeHtml(__('Out of stock')) ?></span></div>
                                    <?php endif; ?>
                                <?php endif; ?>
                            </div>
                            <!-- Add to link: remove -->
                        </div>
                        <?php if ($showDescription) :?>
                            <div class="product description product-item-description">
                                <?= /* @noEscape */ $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                <a href="<?= $block->escapeUrl($_product->getProductUrl()) ?>"
                                   title="<?= /* @noEscape */ $_productNameStripped ?>"
                                   class="action more"><?= $block->escapeHtml(__('Learn More')) ?></a>
                               </div>
                           <?php endif; ?>
                       </div>
                   </div>
               </div>
           </li>

       <?php endforeach; ?>
   </ol>
</div>
<?= $block->getToolbarHtml() ?>
<?php if (!$block->isRedirectToCartEnabled()) :?>
    <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
            "catalogAddToCart": {
            "product_sku": "<?= $block->escapeJs($_product->getSku()) ?>"
        }
    }
}
</script>
<?php endif; ?>
<?php endif; ?>
