<div class="home-block home-block-1">
    <div class="block1-banner-img">
        <?= $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('block1-banner-image')->toHtml(); ?>
    </div>
    <div class="block1-banner-content">
        <div class="block1-banner-main-text">
            <?= $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('block1-banner-main-text')->toHtml(); ?>
        </div>
        <div class="block1-banner-extra-text">
            <?= $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('block1-banner-extra-text')->toHtml(); ?>
        </div>
        <button class="action block1-banner-btn" type="submit">
            <?= $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('block1-banner-btn')->toHtml(); ?>
        </button>
    </div>
</div>

<div class="home-block home-block-2">
    <div class="widget block block-static-block">
        <div class="home-content-top-wrap">
            <div class="home-content-top">
                <div class="content first">
                    <div class="title-mb">
                        <a href="">
                            <?= $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('block2-banner-image-1')->toHtml(); ?>
                        </a>
                    </div>
                    <?= $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('block2-banner-image-1')->toHtml(); ?>
                    <a href=""><?= $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('block2-banner-text-1')->toHtml(); ?></a>
                </div>
                <div class="content second">
                    <div class="title-mb">
                        <a href="">
                            <?= $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('block2-banner-image-2')->toHtml(); ?>
                        </a>
                    </div>
                    <?= $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('block2-banner-image-2')->toHtml(); ?>
                    <a href=""><?= $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('block2-banner-text-2')->toHtml(); ?></a>
                </div>
                <div class="content third">
                    <div class="title-mb">
                        <a href="">
                            <?= $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('block2-banner-image-3')->toHtml(); ?>
                        </a>
                    </div>
                    <?= $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('block2-banner-image-3')->toHtml(); ?>
                    <a href=""><?= $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('block2-banner-text-3')->toHtml(); ?></a>
                </div>
                <div class="content forth mobile-only">
                    <div class="title-mb">
                        <a href="">
                            <?= $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('block2-banner-image-4')->toHtml(); ?>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="home-block home-block-3">
    <div class="widget block block-static-block">
        <div class="home-content-middle-wrap">
            <div class="home-content-middle">
                <div class="widget block block-superfood-block">
                    <div class="title">
                        <?= $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('block3-ingredient-title')->toHtml(); ?>
                        <?= $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('block3-ingredient-des')->toHtml(); ?>
                    </div>
                    <div class="block-superfoods content">
                    <div class="items">
                         <div class="item" id="block-what-are-superfoods-item-1">
                             <div class="superfood-info">
                                <?= $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('block3-icon-1')->toHtml(); ?>
                            </div>
                        </div>
                        <div class="item" id="block-what-are-superfoods-item-2">
                             <div class="superfood-info">
                                <?= $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('block3-icon-2')->toHtml(); ?>
                            </div>
                        </div>
                        <div class="item" id="block-what-are-superfoods-item-3">
                             <div class="superfood-info">
                                <?= $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('block3-icon-3')->toHtml(); ?>
                            </div>
                        </div>
                        <div class="item" id="block-what-are-superfoods-item-4">
                             <div class="superfood-info">
                                <?= $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('block3-icon-4')->toHtml(); ?>
                            </div>
                        </div>
                        <div class="item" id="block-what-are-superfoods-item-5">
                             <div class="superfood-info">
                                <?= $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('block3-icon-5')->toHtml(); ?>
                            </div>
                        </div>
                        <div class="item" id="block-what-are-superfoods-item-6">
                             <div class="superfood-info">
                                <?= $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('block3-icon-6')->toHtml(); ?>
                            </div>
                        </div>
                        <div class="item" id="block-what-are-superfoods-item-7">
                             <div class="superfood-info">
                                <?= $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('block3-icon-7')->toHtml(); ?>
                            </div>
                        </div>
                        <div class="item" id="block-what-are-superfoods-item-8">
                             <div class="superfood-info">
                                <?= $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('block3-icon-8')->toHtml(); ?>
                            </div>
                        </div>
                        <div class="item" id="block-what-are-superfoods-item-9">
                             <div class="superfood-info">
                                <?= $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('block3-icon-9')->toHtml(); ?>
                            </div>
                        </div>
                        <div class="item" id="block-what-are-superfoods-item-10">
                             <div class="superfood-info">
                                <?= $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('block3-icon-10')->toHtml(); ?>
                            </div>
                        </div>
                        <div class="item" id="block-what-are-superfoods-item-11">
                             <div class="superfood-info">
                                <?= $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('block3-icon-11')->toHtml(); ?>
                            </div>
                        </div>
                        <div class="item" id="block-what-are-superfoods-item-12">
                             <div class="superfood-info">
                                <?= $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('block3-icon-12')->toHtml(); ?>
                            </div>
                        </div>
                        <div class="item" id="block-what-are-superfoods-item-13">
                             <div class="superfood-info">
                                <?= $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('block3-icon-13')->toHtml(); ?>
                            </div>
                        </div>
                        <div class="item" id="block-what-are-superfoods-item-14">
                             <div class="superfood-info">
                                <?= $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('block3-icon-14')->toHtml(); ?>
                            </div>
                        </div>
                        <div class="item" id="block-what-are-superfoods-item-15">
                             <div class="superfood-info">
                                <?= $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('block3-icon-15')->toHtml(); ?>
                            </div>
                        </div>
                        <div class="item" id="block-what-are-superfoods-item-16">
                             <div class="superfood-info">
                                <?= $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('block3-icon-16')->toHtml(); ?>
                            </div>
                        </div>
                    </div>
                    <div class="actions">
                        <a href="">
                            <?= $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('block3-shop-contact-btn')->toHtml(); ?>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</div>